### ISSUE TITLE
libp11 uses app_data (ex_data with index=0)

### ISSUE THREAD

**Issue by mtrojnar** [OpenSC/libp11#54]
The incorrect use of ex_data in p11_rsa.c and p11_ec.c may break applications that use the same ex_data index for a different purpose.

**Comment by mtrojnar** [comment]
Fixed by https://github.com/OpenSC/libp11/commit/bb6d30c6fb459b111e7c1beaee8534cd0d9db640.

**Comment by mouse07410** [comment]
This change makes sense, but it did not resolve the problem.
